### ISSUE TITLE
Hazards

### ISSUE THREAD

**Issue by jarljarl** [DIKUGroup6/DIKUGames#124]
Hazards effekter fungerer, men er ligenu inde i powerup

PowerUp benytter sig af StandardBlockBehaviour, som måske er et problem. Hazard skal nemlig have et %-drop chance fra StandardBlockBehaviour, som mangler at blive implementeret

**Comment by Victorschimmell** [comment]
Hazard er vidst stadig en del af powerup, yes?

**Comment by Victorschimmell** [comment]
Nice game modifiers, pisse lækkert
