### ISSUE TITLE
Fix UML class diagram navne

### ISSUE THREAD

**Issue by simonsejse** [DIKUGroup6/DIKUGames#38]
Navne på UML klasse diagrammerne er ikke rigtige på properties, f.eks. er der mange steder vi bruger "_variable" men inde i vores program har vi bare lavet det til en property "Variable" så enten skal det gøres til _variable og lave getters eller så skal vi ændre UML diagrammet..

**Comment by simonsejse** [comment]
Metoder også med :)

**Comment by simonsejse** [comment]
:D

**Comment by simonsejse** [comment]
d

**Comment by Victorschimmell** [comment]
Overført til nyt issue - closed.
